version: '3.9'
services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - '5050:80'
    env_file:
      - ../.env
    volumes:
      - pgadmin4_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgadmin4_data:

networks:
  backend:
    driver: bridge